//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFilter
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int FilterId { get; set; }
    
        public virtual Filter Filter { get; set; }
        public virtual Product Product { get; set; }
    }
}
